<a href="https://colab.research.google.com/github/pawansingh7/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy***

Create a Numpy nd array Object


In [ ]:
import numpy as np

In [ ]:
# 1D array by numpy
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [ ]:
# to check the type of a1
type(a1)

numpy.ndarray

In [ ]:
# 2D array
a2 = np.array([[1,2,3,4],
               [5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# 3D array
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               
               [[10,11.2,12],
               [13,14,15],
               [16,17,18]]])
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11.2, 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [ ]:
# To check the shape of a2
a2.shape

(2, 4)

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
# To check the Dimension of the array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [ ]:
# To check the type of the array
a1.dtype , a2.dtype , a3.dtype

(dtype('int64'), dtype('int64'), dtype('float64'))

In [ ]:
# To check the no. of element in the array
a1.size , a2.size , a3.size

(3, 8, 18)

In [ ]:
# to check the array type
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
# Create a DataFrame from a NumPY array
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

# Creating arrays

In [ ]:
np.ones((2,3), dtype= int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(0,10,2, dtype = float)

array([0., 2., 4., 6., 8.])

In [ ]:
np.random.randint(0,10,size = (3,5))

array([[4, 6, 4, 6, 4],
       [9, 2, 4, 8, 7],
       [0, 7, 5, 7, 5]])

In [ ]:
np.random.randint(100 , size = (5,6))

array([[77, 33, 87, 72, 66, 59],
       [28, 49, 88, 95, 48, 90],
       [32, 88, 54, 28, 76, 58],
       [38, 63, 16, 45, 54, 37],
       [58, 19, 48, 40,  3,  9]])

In [ ]:
np.random.rand(2,2)

array([[0.12906627, 0.41723823],
       [0.14028344, 0.34900852]])

In [ ]:
np.random.seed()
random_arry =  np.random.randint(10,size = (2,3))
random_arry

array([[9, 7, 0],
       [5, 3, 3]])

# Viewing and Slicing

In [ ]:
np.unique(random_arry)

array([0, 3, 5, 7, 9])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11.2, 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [ ]:
a1[0]

1

In [ ]:
a2[1,2]

7

In [ ]:
a3[1,2,1]

17.0

In [ ]:
a3[1,2]

array([16., 17., 18.])

In [ ]:
np.random.seed(seed = 2)
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[8, 8, 6, 2, 8],
         [7, 2, 1, 5, 4],
         [4, 5, 7, 3, 6],
         [4, 3, 7, 6, 1]],

        [[3, 5, 8, 4, 6],
         [3, 9, 2, 0, 4],
         [2, 4, 1, 7, 8],
         [2, 9, 8, 7, 1]],

        [[6, 8, 5, 9, 9],
         [9, 3, 0, 0, 2],
         [8, 8, 2, 9, 6],
         [5, 6, 6, 6, 3]]],


       [[[8, 2, 1, 4, 8],
         [1, 6, 9, 5, 1],
         [2, 4, 7, 6, 4],
         [5, 8, 3, 0, 0]],

        [[5, 7, 5, 0, 8],
         [6, 5, 1, 7, 4],
         [3, 6, 1, 4, 0],
         [8, 5, 4, 2, 9]],

        [[7, 1, 9, 2, 1],
         [0, 7, 1, 8, 9],
         [0, 7, 0, 5, 2],
         [5, 1, 3, 3, 1]]]])

In [ ]:
a4[1,0,0, :5]

array([8, 2, 1, 4, 8])